version: "3.9"
services:
  web:
    build: ./app
    ports:
      - "8080:8000"
    volumes:
      - "./app/src:/app"
  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - data-db:/var/lib/mysql

volumes:
  data-db:
