version: "3.9"
services:
  web-prod:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    env_file: .env
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8000"
    tty: true
  db:
    image: mysql:8.0.32
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql

volumes:
  data-db:
